#!/bin/bash

PASTA="/xmrig/"
clear

# if-else direto para encontrar a pasta
if [ -d "$PASTA" ]; then
    echo "Pasta encontrada: $PASTA"
else
    echo "Pasta não encontrada. Criando..."
    echo "pasta criada"
fi

# Depois segue o select
PS3="Escolha uma opção: "
options=("Listar arquivos" "Mostrar caminho" "Sair")

select opt in "${options[@]}"
do
    case $opt in
        "Listar arquivos")
            ls "$PASTA"
            ;;
        "Mostrar caminho")
            echo "O caminho da pasta é: $PASTA"
            ;;
        "Sair")
            echo "Saindo..."
            break
            ;;
        *)
            echo "Opção inválida."
            ;;
    esac
done
