#!/bin/bash
clear
NOME_PASTA="xmrig"
DIRETORIO_INICIAL="/"

PASTA_ENCONTRADA=$(find "$DIRETORIO_INICIAL" -type d -name "$NOME_PASTA" 2>/dev/null | head -n 1)

if [ -n "$PASTA_ENCONTRADA" ]; then
    echo "Pasta encontrada: $PASTA_ENCONTRADA"
else
    echo "Pasta não encontrada. Criando..."
    mkdir -p "$DIRETORIO_INICIAL/$NOME_PASTA"
    PASTA_ENCONTRADA="$DIRETORIO_INICIAL/$NOME_PASTA"
fi

# Select depois
PS3="Escolha uma opção: "
options=("Listar arquivos" "Mostrar caminho" "Sair")

select opt in "${options[@]}"
do
    case $opt in
        "Listar arquivos")
            ls "$PASTA_ENCONTRADA"
            ;;
        "Mostrar caminho")
            echo "O caminho da pasta é: $PASTA_ENCONTRADA"
            ;;
        "Sair")
            echo "Saindo..."
            break
            ;;
        *)
            echo "Opção inválida."
            ;;
    esac
done
